# Generated by Django 4.1 on 2022-09-03 06:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('address1', models.CharField(max_length=35)),
                ('address2', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
