# Generated by Django 4.1 on 2022-09-03 06:50

import FrontRunner.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontRunner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='null', max_length=254, validators=[FrontRunner.validators.validate_domainonly_email]),
            preserve_default=False,
        ),
    ]
